name: Clone another private repo

on:
  push:
    branches:
      - graphql

jobs:
  clone-build-push-moly-graphql-api:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone your other private repo
        run: |
          git clone --branch graphql_api --single-branch https://x-access-token:${{ secrets.OTHER_REPO_TOKEN }}@github.com/molyorg/moly.git

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: moly
        run: |
          docker build -t yukari/moly:graphql_api .
          docker push yukari/moly:graphql_api