name: Clone another private repo

on:
  push:
    branches:
      - mono

jobs:
  clone-build-push-moly-nextjs-dattk:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone your other private repo
        run: |
          git clone --branch dattk --single-branch https://x-access-token:${{ secrets.OTHER_REPO_TOKEN }}@github.com/molyorg/moly-nextjs.git

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: moly-nextjs
        run: |
          docker build -t yukari/moly:dattk .
          docker push yukari/moly:dattk

  clone-build-push-moly-nextjs-impressifyai:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone your other private repo
        run: |
          git clone --branch impressifyai --single-branch https://x-access-token:${{ secrets.OTHER_REPO_TOKEN }}@github.com/molyorg/moly-nextjs.git

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: moly-nextjs
        run: |
          docker build -t yukari/moly:impressifyai .
          docker push yukari/moly:impressifyai

  clone-build-push-moly-nextjs-kabr2:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone your other private repo
        run: |
          git clone --branch kabr2 --single-branch https://x-access-token:${{ secrets.OTHER_REPO_TOKEN }}@github.com/molyorg/moly-nextjs.git

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: moly-nextjs
        run: |
          docker build -t yukari/moly:kabr2 .
          docker push yukari/moly:kabr2

